spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensedb
    username: root
    password: 12345

  mail:
    host: smtp.gmail.com
    port: 587
    username: kevinpeiris07@gmail.com
    password: ilet zash davh hthe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
